### ISSUE TITLE
Moving forward - cursuri si materiale

### ISSUE THREAD

**Issue by ionescu77** [liviuagache/fcc-repo#1]
## Mozilla - Getting Started with Web Development

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web

## Mozilla - How to Publish your website
https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website

> Are si o sectiune despre gihtub pages, poate e prea devreme pt "hosting and domain name"

> Some tools let you publish your website online:
> 
> GitHub is a "social coding" site. It allows you to upload code repositories for storage in the Git version control system. You can then collaborate on code projects, and the system is open-source by default, meaning that anyone in the world can find your GitHub code, use it, learn from it, and improve on it. GitHub has a very useful feature called GitHub Pages, which allows you to expose website code live on the web.
> Google App Engine is a powerful platform that lets you build and run applications on Google’s infrastructure — whether you need to build a multi-tiered web application from scratch or host a static website. See How do you host your website on Google App Engine? for more information.
> These options are usually free, but you may outgrow the limited feature-set.
>

**Comment by ionescu77** [comment]
La o privire mai atenta in link-ul al doilea postat mai sus scrie si de CodePen, dar scrie si cum sa publici din github, via Github Pages:

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website#publishing_via_github

**Comment by liviuagache** [comment]
Am creat un nou repository https://github.com/liviuagache/liviuagache.github.io cu aceeasi pagina din CodePen, de data asta cu push din Visual Studio Code, clonat prin Terminal PowerShell, dupa tutorialul asta: https://youtu.be/QyFcl_Fba-k?t=69 .
Am incercat sa folosesc imagini locale asa cum mi-ai sugerat, m-am uitat si la Victor Cruceanu si din cate am putut vedea la el a urcat imaginile in repository si in cod le-a pus src=" filename-ul imaginii ". Cred ca am omis eu ceva odata ce am facut lucrurile astea dar nu imi incarca imaginile in pagina... https://liviuagache.github.io/

**Comment by liviuagache** [comment]
> Am creat un nou repository https://github.com/liviuagache/liviuagache.github.io cu aceeasi pagina din CodePen, de data asta cu push din Visual Studio Code, clonat prin Terminal PowerShell, dupa tutorialul asta: https://youtu.be/QyFcl_Fba-k?t=69 .
> Am incercat sa folosesc imagini locale asa cum mi-ai sugerat, m-am uitat si la Victor Cruceanu si din cate am putut vedea la el a urcat imaginile in repository si in cod le-a pus src=" filename-ul imaginii ". Cred ca am omis eu ceva odata ce am facut lucrurile astea dar nu imi incarca imaginile in pagina... https://liviuagache.github.io/

Update: Dupa ce am trimis comentariul am incarcat din nou pagina si le incarca, probabil trebuia sa astept mai mult timp, desi am incercat si dupa 10-15 minute de la ultima modificare. :)

**Comment by ionescu77** [comment]
Bravo man.

Se vede pagina.

Sunt câteva observații de făcut. La cum se vede pe mobil dar le voi scrie în noul repo.

Spre sfârșitul săptămânii o să am timp și eu să mă uit.

Felicitări.

Uneori modificările/schimbările nu apar imediat. Html-ul și imaginile rămân uneori în cache-ul browserului sau al serverului sau pe traseu.

Asta se poate seta din webserver o să ajungem mai încolo.
Sau îți folosești alt browser unde poți face clear cache (că de ex dacă faci clear cache trebuie să te loghezi iar în diverse site-uri gen Facebook, etc.)

Seară bună

**Comment by liviuagache** [comment]
Merci mult pentru aprecieri si incurajari! :)
Voi mai face modificari care sper sa aduca imbunatatirile necesare.
Pe viitor ma gandeam ca pe linkul unde e pagina respectiva sa imi fac un fel de site-portofoliu personal cu linkuri catre alte pagii cum ar fi cea afisata acum si altele pe care le mai fac, eventual si o galerie foto/video cu ce am mai lucrat eu pe partea de fotografie sau editare video, voi avea nevoie de ajutor, indrumari pentru asta cu siguranta.

Inchid acest issue si ne "auzim" pe celalalt repo.
Multumesc mult inca o data!
